import { generate } from '@/lib/rules-generator/generate';
import { ROLES } from '@/lib/security-checklist/data';
import type { RulesAnswers } from '@/lib/rules-generator/types';
import type { ZipEntry } from '@/lib/zip';

function buildChecklistMarkdown(security: RulesAnswers['security']): string {
  const role = ROLES.find((r) => r.id === 'team-lead') ?? ROLES[0]!;
  const lines = [
    '# Cursor Security Checklist (Team Lead)',
    '',
    `_Generated by CursorCraft for **${security}** security sensitivity. Work through in order._`,
    '',
  ];
  for (const item of role.items) {
    lines.push(`- [ ] ${item.label}`);
    lines.push(`  - _Why:_ ${item.why}`);
  }
  return lines.join('\n');
}

function buildReadme(answers: RulesAnswers): string {
  return `# CursorCraft Policy Pack

Generated locally in your browser — nothing was uploaded.

## What's inside

1. \`.cursor/rules/project.mdc\` — project rules tuned for **${answers.language}**${answers.framework ? ` + ${answers.framework}` : ''}
2. \`.cursorignore\` — ignore patterns for secrets and build artifacts
3. \`SECURITY-CHECKLIST.md\` — team lead checklist derived from the CursorCraft security guide

## Next steps

1. Commit these files to your repo root.
2. Run the [Config Analyzer](https://cursorcraft.falling-hall-ac41.workers.dev/tools/config-analyzer) to verify.
3. Enforce Privacy Mode org-wide and review MCP servers with the [MCP Visualizer](https://cursorcraft.falling-hall-ac41.workers.dev/tools/mcp-visualizer).

_Unofficial community resource — not affiliated with Cursor or Anysphere._
`;
}

export function buildPolicyPackFiles(answers: RulesAnswers): ZipEntry[] {
  const config = generate(answers);
  return [
    { name: '.cursor/rules/project.mdc', content: config.rules },
    { name: '.cursorignore', content: config.cursorignore },
    { name: 'SECURITY-CHECKLIST.md', content: buildChecklistMarkdown(answers.security) },
    { name: 'README-POLICY-PACK.md', content: buildReadme(answers) },
  ];
}
