export type SnippetTarget = 'husky' | 'github-action' | 'gitlab-ci';

export interface PrecommitOptions {
  /** Also scan mcp.json and settings.json */
  scanExtended?: boolean;
}

const SCAN_FILES = [
  '.cursor/rules',
  '.cursorrules',
  'hooks.json',
  '.cursor/hooks.json',
];

const EXTENDED_FILES = ['.cursor/mcp.json', '.cursor/settings.json', 'settings.json'];

export function generatePrecommitSnippet(target: SnippetTarget, options: PrecommitOptions = {}): string {
  const files = options.scanExtended ? [...SCAN_FILES, ...EXTENDED_FILES] : SCAN_FILES;

  if (target === 'husky') {
    return generateHusky(files);
  }
  if (target === 'gitlab-ci') {
    return generateGitLab(files);
  }
  return generateGitHubAction(files);
}

function fileListComment(files: string[]): string {
  return files.map((f) => `#   - ${f}`).join('\n');
}

function generateHusky(files: string[]): string {
  return `#!/usr/bin/env sh
# CursorCraft pre-commit — block secrets in Cursor config files
# Generated by https://cursorcraft.falling-hall-ac41.workers.dev/tools/precommit-snippet
# Scans:
${fileListComment(files)}

set -e

PATTERNS=(
  'sk-[a-zA-Z0-9]\\{16,\\}'
  'sk-ant-[a-zA-Z0-9_-]\\{16,\\}'
  'api[_-]?key[[:space:]]*[:=]'
  'secret[[:space:]]*[:=]'
  'password[[:space:]]*[:=]'
  'token[[:space:]]*[:=]'
)

scan_file() {
  f="$1"
  [ -f "$f" ] || return 0
  for p in "\${PATTERNS[@]}"; do
    if grep -qE "$p" "$f" 2>/dev/null; then
      echo "CursorCraft: possible secret in $f (matched: $p)" >&2
      echo "Remove the secret, rotate it, and use environment variables." >&2
      exit 1
    fi
  done
}

# Flat files
for f in .cursorrules hooks.json .cursor/hooks.json .cursor/mcp.json .cursor/settings.json settings.json; do
  scan_file "$f"
done

# Rules directory
if [ -d .cursor/rules ]; then
  find .cursor/rules -type f \\( -name '*.mdc' -o -name '*.md' \\) 2>/dev/null | while read -r f; do
    scan_file "$f"
  done
fi

echo "CursorCraft: Cursor config secret scan passed."
`;
}

function generateGitHubAction(files: string[]): string {
  return `# CursorCraft config secret scan — add to .github/workflows/
# Scans:
${fileListComment(files)}

name: Cursor config secret scan

on:
  pull_request:
    paths:
      - '.cursor/**'
      - '.cursorrules'
      - 'hooks.json'
      - '.cursor/hooks.json'
      - 'settings.json'

jobs:
  cursor-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Block secrets in Cursor config
        run: |
          set -e
          PATTERNS=(
            'sk-[a-zA-Z0-9]{16,}'
            'sk-ant-[a-zA-Z0-9_-]{16,}'
            'api[_-]?key[[:space:]]*[:=]'
            'secret[[:space:]]*[:=]'
            'password[[:space:]]*[:=]'
            'token[[:space:]]*[:=]'
          )
          scan() {
            f="$1"
            [ -f "$f" ] || return 0
            for p in "\${PATTERNS[@]}"; do
              if grep -qE "$p" "$f"; then
                echo "::error file=$f::Possible secret in Cursor config (matched $p)"
                exit 1
              fi
            done
          }
          for f in .cursorrules hooks.json .cursor/hooks.json .cursor/mcp.json .cursor/settings.json settings.json; do
            scan "$f"
          done
          if [ -d .cursor/rules ]; then
            find .cursor/rules -type f \\( -name '*.mdc' -o -name '*.md' \\) -print0 | while IFS= read -r -d '' f; do
              scan "$f"
            done
          fi
`;
}

function generateGitLab(files: string[]): string {
  return `# CursorCraft config secret scan — add to .gitlab-ci.yml
# Scans:
${fileListComment(files)}

cursor-config-secrets:
  stage: test
  image: alpine:3.20
  rules:
    - changes:
        - .cursor/**/*
        - .cursorrules
        - hooks.json
        - settings.json
  script:
    - apk add --no-cache grep findutils
    - |
      set -e
      for f in .cursorrules hooks.json .cursor/hooks.json; do
        [ -f "$f" ] && grep -qE 'sk-[a-zA-Z0-9]{16,}|api[_-]?key|secret|password|token' "$f" && exit 1 || true
      done
      if [ -d .cursor/rules ]; then
        find .cursor/rules -type f -name '*.mdc' -exec grep -qE 'sk-[a-zA-Z0-9]{16,}|api[_-]?key' {} \\; && exit 1 || true
      fi
`;
}
