import type { AuditResult, Severity } from './types.ts';

const SEVERITY_LABEL: Record<Severity, string> = {
  critical: 'Critical',
  warning: 'Warning',
  tip: 'Tip',
};

/** Format audit findings as shareable Markdown (for tickets, PRs, or team docs). */
export function formatAuditMarkdown(result: AuditResult): string {
  const lines: string[] = [
    '# Cursor Config Audit Report',
    '',
    `_Generated by [CursorCraft](https://cursorcraft.falling-hall-ac41.workers.dev/tools/config-analyzer) — local-first, nothing uploaded._`,
    '',
    '## Summary',
    '',
    `- **Files reviewed:** ${result.filesProvided}`,
    `- **Findings:** ${result.findings.length} (${result.counts.critical} critical · ${result.counts.warning} warning · ${result.counts.tip} tip)`,
    '',
  ];

  if (result.findings.length === 0) {
    lines.push('No findings — your provided config looks clean for the checks we run.', '');
    return lines.join('\n');
  }

  let currentSeverity: Severity | null = null;
  for (const finding of result.findings) {
    if (finding.severity !== currentSeverity) {
      currentSeverity = finding.severity;
      lines.push(`## ${SEVERITY_LABEL[currentSeverity]}`, '');
    }
    lines.push(`### ${finding.title}`, '');
    lines.push(`**Source:** \`${finding.source}\`  `);
    lines.push(`**Why it matters:** ${finding.explanation}`, '');
    lines.push(`**Fix:** ${finding.fix}`, '');
  }

  lines.push('---', '', '_Run a fresh audit after changes: https://cursorcraft.falling-hall-ac41.workers.dev/tools/config-analyzer_');
  return lines.join('\n');
}

export function downloadMarkdown(content: string, filename = 'cursorcraft-audit.md'): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
